config/routes.rb
Annoyingly::Application.routes.draw do

  resources :tickets

  resource :user, only: [ :new, :create ]
  resource :user_session, only: [ :new, :create, :destroy ]
  resources :emails, only: [ :create ]

  get 'login' => 'user_sessions#new'
  get 'logout' => 'user_sessions#destroy'
  get 'register' => 'users#new'

  root to: 'tickets#index'
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :from, :html, :plain, :subject

  belongs_to :ticket

  validates :from, presence: true
  validates :subject, presence: true
  validates :plain, presence: true

  before_create :create_ticket
  after_create :notify_employee

  def to_s
    subject
  end

  def code
    ticket.code
  end

  private

  def create_ticket
    self.ticket = Ticket.create!
  end

  def notify_employee
    TicketMailer.notify_employee(self, User.random).deliver
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  has_many :messages
  before_create :set_code

  def to_s
    messages.first.to_s
  end

  def set_code
    self.code = SecureRandom.hex(10)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  attr_accessible :password, :email, :password_confirmation

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true

  def avatar_url(size=48)
    gravatar_id = Digest::MD5::hexdigest(email).downcase
    "https://secure.gravatar.com/avatar/#{gravatar_id}.png?s=#{size}&d=retro"
  end

  def to_s
    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate

  private

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  helper_method :current_user

  def authenticate
    redirect_to login_path unless current_user
  end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :authenticate
  before_filter :verify_signature

  def create
    message = Message.new
    message.from = params[:from]
    message.subject = params[:subject]
    message.html = params[:html]
    message.plain = params[:plain]
    message.save!
    render nothing: true, status: 200
  end

  private

  def verify_signature
    sig_params = request.request_parameters.clone
    provided = sig_params.delete(:signature)
    signature = Digest::MD5.hexdigest(flatten_params(sig_params).sort.map{|k,v| v}.join + ENV['CLOUDMAILIN_SECRET'])

    if provided != signature
      render :text => "Message signature fail #{provided} != #{signature}", :status => 403, :content_type => Mime::TEXT.to_s
      return false
    end
  end

  def flatten_params(params, title = nil, result = {})
    params.each do |key, value|
      if value.kind_of?(Hash)
        key_name = title ? "#{title}[#{key}]" : key
        flatten_params(value, key_name, result)
      else
        key_name = title ? "#{title}[#{key}]" : key
        result[key_name] = value
      end
    end

    return result
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_filter :authenticate

  def new
  end

  def create
    user = User.find_by_email(params[:user_session][:email])
    if user and user.authenticate(params[:user_session][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authenticate

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title annoying.ly
    = stylesheet_link_tag    "application", media: "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
%body
  .navbar.navbar-fixed-top
    .navbar-inner
      .container
        = link_to "annoying.ly", root_path, class: 'brand'
        - unless current_user
          %ul.nav
            %li= link_to "Login", login_path
            %li= link_to "Register", register_path
        - if current_user
          %ul.nav
            %li= link_to "Tickets", tickets_path
          .btn-group.pull-right
            %a.btn.dropdown-toggle{ href: '#', data: { toggle: :dropdown } }
              %img{ src: current_user.avatar_url(16) }
              = current_user
              %span.caret
            %ul.dropdown-menu
              %li= link_to "Logout", logout_path
  - if flash[:alert]
    .container
      .alert.alert-error= flash[:alert]
  - if flash[:notice]
    .container
      .alert.alert-info= flash[:notice]
  - if flash[:warning]
    .container
      .alert.alert-warning= flash[:warning]
  - if flash[:success]
    .container
      .alert.alert-success= flash[:success]
  .container
    = yield

app/views/tickets/index.html.haml
%h1 Tickets
%ul
  - @tickets.each do |ticket|
    %li= ticket

app/views/user_sessions/new.html.haml
%h1 Login
= simple_form_for :user_session, url: user_session_path do |f|
  = f.input :email
  = f.input :password
  = f.submit "Login", class: "btn btn-primary"

app/views/users/create.html.erb
you created a user

app/views/users/create.html.haml
you created a user

app/views/users/new.html.haml
%h1 Register
= simple_form_for @user, url: user_path do |f|
  = f.input :email
  = f.input :password
  = f.input :password_confirmation
  = f.submit class: 'btn btn-primary'